# Site metadata
keywords: Cryptography, Privacy, Digital Signatures, Post-Quantum Cryptography, Universität der Bundeswehr München, Research Institute CODE, Munich, Germany, Austria, Research, Professor
description: Prof. Dr. Daniel Slamanig, Universität der Bundeswehr München, Munich, Germany
title: Prof. Dr. Daniel Slamanig | Universität der Bundeswehr München | Research Institute CODE 

author: Daniel Slamanig
authorimg: images/daniel_web.jpg
authoroccup: Full Professor of Cryptology

#inst: IAIK
#insturl: http://www.iaik.tugraz.at
uni: Universität der Bundeswehr München 
uniurl: https://www.unibw.de/home

stackex: users/3352097/drlecter
bluesky: drl3c7er
orcid: 0000-0002-4181-2561
linkedin: danielslamanig
dblp: hd/s/Slamanig:Daniel
scholar: DoAyhP4AAAAJ
keybase: drl3c7er

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
collections:
  - preprints
  - proc
  - articles
  - articlesworeview
  - books
  - theses
  - deli
include:
  - keybase.txt
exclude:
  - Gemfile
  - Gemfile.lock
