# Site metadata
keywords: Cryptography, Privacy, Digital Signatures, Security, AIT Austrian Institute of Technology
description: Homepage of Daniel Slamanig, AIT Austrian Institute of Technology, Vienna, Austria
title: Homepage of Daniel Slamanig | AIT Austrian Institute of Technology

author: Daniel Slamanig
authorimg: images/ds.png
authoroccup: Researcher in Cryptography

#inst: IAIK
#insturl: http://www.iaik.tugraz.at
uni: AIT Austrian Institute of Technology
uniurl: https://www.ait.ac.at

stackex: users/3352097/drlecter
twitter: drl3c7er
linkedin: danielslamanig
dblp: hd/s/Slamanig:Daniel
scholar: DoAyhP4AAAAJ

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
collections:
  - preprints
  - proc
  - articles
  - books
  - theses
  - deli
exclude:
  - Gemfile
  - Gemfile.lock
